// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDietitianMobileApp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyDietitianMobileApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109222909_AddPremiumFields")]
    partial class AddPremiumFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.AccessKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId", "ClientId");

                    b.ToTable("AccessKeys");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveDietitianId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PremiumActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProgramEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProgramStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDietitianId");

                    b.HasIndex("DietitianId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ComplianceScoreConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<int>("MandatoryAlternative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7);

                    b.Property<int>("MandatoryDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("MandatorySkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("OptionalDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("OptionalSkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId");

                    b.HasIndex("DietitianId");

                    b.HasIndex("DietitianId", "DietPlanId")
                        .IsUnique();

                    b.ToTable("ComplianceScoreConfigs");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId");

                    b.HasIndex("ClientId", "Status");

                    b.ToTable("DietPlans");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DailyTargetCalories")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DietPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietPlanId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId");

                    b.HasIndex("DietPlanId1");

                    b.HasIndex("DietPlanId", "Date")
                        .IsUnique();

                    b.ToTable("DietPlanDays");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DietPlanDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietPlanDayId1")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlannedRecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanDayId");

                    b.HasIndex("DietPlanDayId1");

                    b.HasIndex("DietPlanDayId", "Type");

                    b.ToTable("DietPlanMeals");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Dietitian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Dietitians");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProhibited")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecipeId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecipeId2")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("IsActive");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RecipeId1");

                    b.HasIndex("RecipeId2");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealCompliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlternativeRecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DietPlanMealId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietPlanMealId");

                    b.ToTable("MealCompliances");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("DietPlanMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanMealId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealItemCompliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlternativeIngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ClientTimezoneOffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("DietDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietDayId");

                    b.HasIndex("DietPlanId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MarkedAt");

                    b.HasIndex("MealId");

                    b.HasIndex("MealItemId");

                    b.HasIndex("ClientId", "DietPlanId");

                    b.HasIndex("ClientId", "MarkedAt");

                    b.HasIndex("ClientId", "MealItemId", "DietDayId")
                        .IsUnique();

                    b.ToTable("MealItemCompliance");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.AccessKey", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", null)
                        .WithMany("AccessKeys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", null)
                        .WithMany("Clients")
                        .HasForeignKey("DietitianId");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanDay", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlan", null)
                        .WithMany()
                        .HasForeignKey("DietPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlan", "DietPlan")
                        .WithMany("Days")
                        .HasForeignKey("DietPlanId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietPlan");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanDay", null)
                        .WithMany()
                        .HasForeignKey("DietPlanDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanDay", "DietPlanDay")
                        .WithMany("Meals")
                        .HasForeignKey("DietPlanDayId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietPlanDay");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany("MandatoryIngredients")
                        .HasForeignKey("RecipeId");

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany("OptionalIngredients")
                        .HasForeignKey("RecipeId1");

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany("ProhibitedIngredients")
                        .HasForeignKey("RecipeId2");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealCompliance", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", "DietPlanMeal")
                        .WithMany()
                        .HasForeignKey("DietPlanMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DietPlanMeal");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", null)
                        .WithMany("Items")
                        .HasForeignKey("DietPlanMealId");

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealItemCompliance", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanDay", null)
                        .WithMany()
                        .HasForeignKey("DietDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlan", null)
                        .WithMany()
                        .HasForeignKey("DietPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.MealItem", null)
                        .WithMany()
                        .HasForeignKey("MealItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", null)
                        .WithMany("Recipes")
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.Navigation("AccessKeys");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanDay", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Dietitian", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("MandatoryIngredients");

                    b.Navigation("OptionalIngredients");

                    b.Navigation("ProhibitedIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
