// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDietitianMobileApp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyDietitianMobileApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.AccessKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId", "ClientId");

                    b.ToTable("AccessKeys");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveDietitianId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProgramEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProgramStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDietitianId");

                    b.HasIndex("DietitianId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Dietitian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Dietitians");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProhibited")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecipeId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecipeId2")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RecipeId1");

                    b.HasIndex("RecipeId2");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.AccessKey", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", null)
                        .WithMany("AccessKeys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", null)
                        .WithMany("Clients")
                        .HasForeignKey("DietitianId");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany("MandatoryIngredients")
                        .HasForeignKey("RecipeId");

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany("OptionalIngredients")
                        .HasForeignKey("RecipeId1");

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany("ProhibitedIngredients")
                        .HasForeignKey("RecipeId2");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", null)
                        .WithMany("Recipes")
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.Navigation("AccessKeys");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Dietitian", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("MandatoryIngredients");

                    b.Navigation("OptionalIngredients");

                    b.Navigation("ProhibitedIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
